version: "3.6"

services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    ports:
      - 127.0.0.1:9042:9042
    volumes:
      - cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_DC=dc1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

volumes:
  cassandra:
    name: cassandra

networks:
  default:
    name: scalar-network
